<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="true"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Defusal Protocol // Bomb Simulator</title>
    <!-- Link to the separated CSS file -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

    <!-- MAIN MENU -->
    <div id="screen-menu" class="screen active">
        <div class="menu-container">
            <h1 class="menu-title">DEFUSAL PROTOCOL</h1>
            <p style="color: var(--text-muted); letter-spacing: 2px;">SELECT SECURITY TIER</p>
            <div class="level-grid" id="levelGrid">
                <!-- Generated by JS -->
            </div>
            <button class="btn-abort" onclick="window.location.href='../index.jsp'" style="margin-top: 30px;">EXIT TO HUB</button>
        </div>
    </div>

    <!-- GAMEPLAY CHASSIS -->
    <div id="screen-game" class="screen">
        <div class="briefcase">
            <div class="header">
                <button class="btn-abort" onclick="abortToMenu()">&#9888; ABORT</button>
                <div class="timer-container">
                    <div class="timer-label">DETONATION IN</div>
                    <div class="timer" id="timerDisplay">03:00:00</div>
                </div>
                <div class="strikes-container">
                    <div class="strikes-label">SYSTEM INTEGRITY</div>
                    <div class="led-group">
                        <div class="led" id="strike1"></div>
                        <div class="led" id="strike2"></div>
                        <div class="led" id="strike3"></div>
                    </div>
                </div>
            </div>

            <div class="grid-container" id="moduleGrid">
                <!-- Modules injected by JS -->
            </div>

            <!-- Mini Game Interaction Overlay -->
            <div class="minigame-overlay" id="miniGameOverlay">
                <div class="minigame-box">
                    <h2 id="mgTitle" style="color: var(--neon-blue);">MODULE OVERRIDE</h2>
                    <p id="mgDesc">Execute sequence to bypass security.</p>
                    <div style="font-size: 2rem; margin: 20px 0;" id="mgTarget">0 / 3</div>
                    <button class="hack-btn" id="hackBtn">EXECUTE OVERRIDE</button>
                    <br><br>
                    <button class="btn-abort" onclick="closeMiniGame(false)" style="margin-top: 10px;">CANCEL</button>
                </div>
            </div>
        </div>
    </div>

    <!-- GAME OVER / SUCCESS SCREENS -->
    <div id="screen-result" class="screen">
        <div class="ending-box" id="resultBox">
            <h1 id="resultTitle" style="font-size: 4rem; margin: 0;"></h1>
            <p id="resultSub"></p>
            <button class="btn-abort" style="margin-top: 20px;" onclick="abortToMenu()">RETURN TO MENU</button>
        </div>
    </div>

    <!-- Link to the separated JavaScript file -->
    <script src="js/engine.js"></script>
</body>
</html>